[project]
name = 'decentralized-journalism-platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.news-verification-engine]
path = 'contracts/news-verification-engine.clar'
clarity_version = 2
epoch = 2.5

[contracts.reader-funding-distributor]
path = 'contracts/reader-funding-distributor.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
